name: tcc_v2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^4.2.1
  cloud_firestore: ^6.1.0
  show_hide_password: ^0.0.2
  firebase_auth: ^6.1.2
  get: ^4.7.2
  timezone: ^0.10.1
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: Alegreya
      fonts:
        - asset: assets\fonts\Alegreya-Medium.ttf
          weight: 500
        - asset: assets\fonts\Alegreya-Regular.ttf
          weight: 400
  assets:
  - assets\images\userAvatar.jpg
  - assets\images\avatar.png

flutter_native_splash:
  android: true
  color: "#253334"
  image: "assets/images/app/iconFacility.png"
  android_12:
    color: "#253334"

flutter_icons:
  image_path: "assets/images/app/iconFacility1.png"
  ios: true
  remove_alpha_ios: true
  android: "launcher_icon"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/app/iconFacility.png"